name: Release

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # autorise le bot à pousser les tags et commits
      issues: write        # pour publier sur GitHub Releases
      pull-requests: write # facultatif mais recommandé
      id-token: write      # utile pour npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install

      - run: bun run build

      - name: Release package
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
